# Generated by Django 5.1.4 on 2025-05-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory2',
            options={'ordering': ['date'], 'verbose_name': '현재고', 'verbose_name_plural': '현재고 목록'},
        ),
        migrations.AlterUniqueTogether(
            name='rfidscan',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='defaultinventory',
            name='expiry_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='defaultinventory',
            name='medication_lot_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='defaultinventory',
            name='pie_healthcare_num',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventory2',
            name='expiry_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory2',
            name='medication_lot_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventory2',
            name='pie_healthcare_num',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventorydiscrepancy',
            name='expiry_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorydiscrepancy',
            name='medication_lot_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventorydiscrepancy',
            name='pie_healthcare_num',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rfidscan',
            name='expiry_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='rfidscan',
            name='medication_lot_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rfidscan',
            name='pie_healthcare_num',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specification',
            name='expiry_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='specification',
            name='medication_lot_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specification',
            name='pie_healthcare_num',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='defaultinventory',
            index=models.Index(fields=['pie_healthcare_num', 'expiry_date', 'medication_lot_number'], name='inventory2__pie_hea_2f2926_idx'),
        ),
    ]
